version: "3.9"

networks:
  default:
  proxy:
    external:
      name: proxy

services:
  web:
    build: .
    image: msawatzky75/generator-web
    environment:
      - LETSENCRYPT_HOST=gen.msawatzky75.com
      - VIRTUAL_HOST=gen.msawatzky75.com
    networks:
      - proxy
